---
stages:
  - lint
  - build

lint:yaml:
  stage: lint
  image: sdesbure/yamllint
  before_script:
    - yamllint --version
  script:
    - LIST_OF_YAML=$(find -path '.git' -prune -o -print | egrep "\.ya?ml$")
    - yamllint --strict --config-file .yamllint.yaml $LIST_OF_YAML

lint:markdown:
  stage: lint
  image:
    name: 06kellyjac/markdownlint-cli
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  before_script:
    - markdownlint --version
  script:
    - LIST_OF_MARKDOWN=$(find -path '.git' -prune -o -print | egrep "\.md$" | tr '\n' ' ')
    - markdownlint $LIST_OF_MARKDOWN

lint:docker:
  stage: lint
  image:
    name: hadolint/hadolint:latest-debian
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  before_script:
    - hadolint --version
  script:
    - LIST_OF_DOCKERFILES=$(find -path '.git' -prune -o -print | egrep ".*Dockerfile")
    - hadolint $LIST_OF_DOCKERFILES

build:docker:latest:
  stage: build
  only:
    - master
  image: docker
  services:
    - docker:dind
  before_script:
    - docker --version
  script:
    - .scripts/ci_build.sh

build:docker:latest-slim:
  stage: build
  only:
    - master
  image: docker
  services:
    - docker:dind
  before_script:
    - docker --version
  script:
    - .scripts/ci_build.sh

build:docker:0.13.0:
  stage: build
  only:
    - master
  image: docker
  services:
    - docker:dind
  before_script:
    - docker --version
  script:
    - .scripts/ci_build.sh

build:docker:0.13.0-slim:
  stage: build
  only:
    - master
  image: docker
  services:
    - docker:dind
  before_script:
    - docker --version
  script:
    - .scripts/ci_build.sh

build:docker:0.12.0:
  stage: build
  only:
    - master
  image: docker
  services:
    - docker:dind
  before_script:
    - docker --version
  script:
    - .scripts/ci_build.sh

build:docker:0.12.0-slim:
  stage: build
  only:
    - master
  image: docker
  services:
    - docker:dind
  before_script:
    - docker --version
  script:
    - .scripts/ci_build.sh

build:docker:0.11.0:
  stage: build
  only:
    - master
  image: docker
  services:
    - docker:dind
  before_script:
    - docker --version
  script:
    - .scripts/ci_build.sh

build:docker:0.11.0-slim:
  stage: build
  only:
    - master
  image: docker
  services:
    - docker:dind
  before_script:
    - docker --version
  script:
    - .scripts/ci_build.sh

build:docker:0.10.0:
  stage: build
  only:
    - master
  image: docker
  services:
    - docker:dind
  before_script:
    - docker --version
  script:
    - .scripts/ci_build.sh

build:docker:0.10.0-slim:
  stage: build
  only:
    - master
  image: docker
  services:
    - docker:dind
  before_script:
    - docker --version
  script:
    - .scripts/ci_build.sh
