---
stages:
  - lint
  - poll


lint:shell:
  stage: lint
  image: docker
  services:
    - docker:dind
  before_script:
    - docker --version
  script:
    - LIST_OF_SHELL=$(find -path '.git' -prune -o -print | egrep "\.sh$")
    - docker run -v "$PWD:/mnt" koalaman/shellcheck $LIST_OF_SHELL
  except:
    - schedules

lint:yaml:
  stage: lint
  image: sdesbure/yamllint
  before_script:
    - yamllint --version
  script:
    - yamllint --strict --config-file .yamllint.yaml .
  except:
    - schedules

# Common markdown config
.markdown: &markdown
  stage: lint
  image:
    name: registry.gitlab.com/06kellyjac/docker_markdownlint-cli
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  before_script:
    - markdownlint --version
  script:
    - markdownlint .
  except:
    - schedules

lint:markdown:docker_hub:
  <<: *markdown
  image:
    name: 06kellyjac/markdownlint-cli

lint:markdown:gitlab:
  <<: *markdown


poll:npm:
  stage: poll
  image: node:alpine
  before_script:
    - node --version
    - npm --version
  script:
    - .scripts/poll_npm_version.sh
  only:
    - schedules
    - web

poll:docker_hub:
  stage: poll
  image: alpine
  script:
    - .scripts/poll_node_docker_hub.sh
  only:
    - schedules
    - web
